# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master
- develop

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  displayName: 'Flutter Install'

- task: FlutterTest@0
  displayName: 'Flutter Test'

- task: FlutterBuild@0
  displayName: 'Flutter Build'
  inputs:
    target: all
  
- task: PublishBuildArtifacts@1
  displayName: "Publish Android apk"
  inputs:
    PathtoPublish: build/app/outputs/apk/release/app-release.apk

- task: PublishBuildArtifacts@1
  displayName: "Publish iOS app"
  inputs:
    PathtoPublish: /build/ios/iphoneos/Runner.app
